const fallbackStories=[
 {category:'research',title:'A new benchmark asks what models do after the answer',dek:'Researchers introduce a test for long-horizon reliability — and find that confident models still lose the plot when tools enter the loop.',source:'NATURE AI',time:'2h ago',tag:'Research',url:'https://www.nature.com/'},
 {category:'product',title:'The agent era gets its first real productivity suite',dek:'A familiar set of tools, now designed around delegation rather than prompting. The result is less magical than useful — which may be the point.',source:'THE VERGE',time:'4h ago',tag:'Product',url:'https://www.theverge.com/'},
 {category:'policy',title:'The world’s first frontier model audit rules take shape',dek:'A cross-border working group publishes a practical framework for evaluating the systems that are too powerful to assess with vibes alone.',source:'MIT TECH REVIEW',time:'6h ago',tag:'Policy',url:'https://www.technologyreview.com/'},
 {category:'product',title:'Open weights, smaller footprint: the model to watch',dek:'A compact release matches yesterday’s flagship on the tasks people actually use, while fitting on hardware that does not need a data center.',source:'HUGGING FACE',time:'8h ago',tag:'Open models',url:'https://huggingface.co/blog'}
];
let stories=fallbackStories;let active='all';
const list=document.querySelector('#storyList'),empty=document.querySelector('#emptyState');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(items){list.innerHTML=items.map(s=>`<article class="story"><div class="story-number">${String(stories.indexOf(s)+1).padStart(2,'0')}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.dek||'A new development worth understanding in the fast-moving AI landscape.')}</p><div class="story-tags"><span class="tag">${esc(s.tag||s.category||'AI')}</span><span>${esc(s.time||'Today')}</span><button class="story-detail-btn" data-story="${stories.indexOf(s)}">Evidence desk ↗</button></div></div><div class="story-source"><strong>${esc(s.source)}</strong>Evidence linked</div></article>`).join('');empty.hidden=items.length!==0}
function filter(){const q=document.querySelector('#searchInput').value.toLowerCase();render(stories.filter(s=>(active==='all'||s.category===active)&&(!q||`${s.title} ${s.dek} ${s.source}`.toLowerCase().includes(q))))}
function openDrawer(story){const claims=story.claims?.length?story.claims:[{claim:story.title,supported:true,evidence_urls:story.url?[story.url]:[],excerpt:'Primary source link retained for the reviewed edition.'}];document.querySelector('#drawerTitle').textContent=story.title;document.querySelector('#drawerWhy').textContent=story.dek||'Evidence-backed context for this edition.';document.querySelector('#claimList').innerHTML=claims.map(claim=>`<div class="claim"><p>${esc(claim.claim)}</p><span class="claim-status">${claim.supported?'Supported by the panel':'Not supported — held from publication'}</span><div class="claim-evidence">${(claim.evidence_urls||[]).map((url,i)=>`<a href="${esc(url)}" target="_blank" rel="noreferrer">Source ${i+1} ↗</a>`).join('')}</div>${claim.excerpt?`<p class="evidence-excerpt">“${esc(claim.excerpt)}”</p>`:''}</div>`).join('');const corrections=story.corrections||[];document.querySelector('#correctionSection').hidden=!corrections.length;document.querySelector('#correctionList').innerHTML=corrections.map(c=>`<div class="correction"><strong>${esc(c.correction||c.corrected_text)}</strong><div>Changed from: ${esc(c.claim||c.original_text)}</div><time>${esc(c.created_at||c.date||'Edition correction')} · ${esc(c.reason||'Editorial correction')}</time></div>`).join('');const source=document.querySelector('#drawerSource');source.href=story.url||'#';document.querySelector('#storyBackdrop').hidden=false;document.querySelector('#storyDrawer').classList.add('open');document.querySelector('#storyDrawer').setAttribute('aria-hidden','false')}
function closeDrawer(){document.querySelector('#storyDrawer').classList.remove('open');document.querySelector('#storyDrawer').setAttribute('aria-hidden','true');setTimeout(()=>document.querySelector('#storyBackdrop').hidden=true,300)}
list.addEventListener('click',e=>{const btn=e.target.closest('[data-story]');if(btn)openDrawer(stories[Number(btn.dataset.story)])});document.querySelector('#drawerClose').addEventListener('click',closeDrawer);document.querySelector('#storyBackdrop').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
render(stories);Promise.all([fetch('data/news.json').then(r=>r.json()),fetch('data/corrections.json').then(r=>r.json()).catch(()=>({}))]).then(([data,corrections])=>{if(data.stories?.length){const correctionRows=corrections.corrections||[];stories=data.stories.map(s=>({...s,tag:s.category,corrections:s.corrections||correctionRows.filter(c=>c.story_id===s.event_id||c.story_id===s.id)}));render(stories)}}).catch(()=>{});
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');active=btn.dataset.filter;filter()}));document.querySelector('#searchInput').addEventListener('input',filter);
function subscribe(){const email=prompt('Where should we send the daily signal?');if(email){document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),4000)}}
document.querySelector('#subscribeBtn').addEventListener('click',subscribe);document.querySelector('#asideSubscribe').addEventListener('click',subscribe);document.querySelector('#themeToggle').addEventListener('click',()=>document.body.classList.toggle('dark'));document.querySelector('#menuBtn').addEventListener('click',()=>document.querySelector('.main-nav').classList.toggle('mobile-open'));
