const fallbackReviews=[
 {id:'cluster-001',status:'pending',category:'RESEARCH',source:'ARXIV · 2 sources',title:'A benchmark asks what models do after the answer',summary:'Researchers test long-horizon reliability and find that confident models still lose the plot when tools enter the loop.',reason:'Evidence is strong, but the panel disagrees on whether the result is a step-change or a careful increment.',votes:['AL','RK','MO','JP'],decision:null,url:'https://arxiv.org'},
 {id:'cluster-002',status:'escalated',category:'POLICY',source:'MIT TECHNOLOGY REVIEW · 3 sources',title:'Frontier model audit rules take shape',summary:'A cross-border working group publishes a practical framework for evaluating systems that are too powerful to assess with vibes alone.',reason:'Legal and policy implications require a human read before publication.',votes:['AL','RK','MO','JP'],decision:null,url:'https://www.technologyreview.com'},
 {id:'cluster-003',status:'pending',category:'PRODUCT',source:'THE VERGE · 4 sources',title:'The agent era gets its first real productivity suite',summary:'A familiar set of tools, now designed around delegation rather than prompting. Less magical than useful may be the point.',reason:'The sources agree on the launch, but not on the independence of the reporting.',votes:['AL','RK','JP','MO'],decision:null,url:'https://www.theverge.com/'}
];
const fallbackSources=[['OpenAI News','openai-news','Healthy','94%','4'],['Google DeepMind','deepmind-blog','Healthy','100%','6'],['Anthropic','anthropic-news','Healthy','100%','3'],['Microsoft Research','microsoft-research','Healthy','88%','2'],['Hugging Face','huggingface-blog','Healthy','100%','5'],['MIT Technology Review','mit-tech-review','Warning','71%','1'],['The Verge AI','the-verge-ai','Healthy','93%','4'],['Ars Technica AI','ars-technica-ai','Healthy','100%','3']];
const fallbackAlerts=[{severity:'warn',title:'MIT Technology Review · source latency',detail:'Last successful response was 7h ago. Cooldown active.',time:'Today · 05:58 UTC'},{severity:'critical',title:'No open incidents',detail:'All critical alerts recovered in the last 14 editions.',time:'Yesterday · 06:42 UTC'}];
let reviews=loadLocal('reviews',fallbackReviews), sourceRows=fallbackSources, alertRows=fallbackAlerts, activeRunId=null;
async function apiRequest(path, options={}){const response=await fetch(path,{...options,credentials:'same-origin',headers:{'content-type':'application/json',...(options.headers||{})}});if(response.status===401){window.location.href=`/auth/login?returnTo=${encodeURIComponent(location.pathname+location.search)}`;throw Error('Authentication required');}if(!response.ok)throw Error((await response.json().catch(()=>({}))).error||`API request failed (${response.status})`);return response.json()}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadLocal(key,fallback){try{return JSON.parse(localStorage.getItem(`ai-daily-${key}`))||fallback}catch{return fallback}}
function save(){localStorage.setItem('ai-daily-reviews',JSON.stringify(reviews))}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
function renderReviews(){const filter=document.querySelector('#queueFilter').value;const items=reviews.filter(item=>filter==='all'||item.status===filter);document.querySelector('#queueCount').textContent=String(reviews.filter(x=>!x.decision).length).padStart(2,'0');document.querySelector('#queueMetric').textContent=String(reviews.filter(x=>!x.decision).length).padStart(2,'0');document.querySelector('#reviewEmpty').hidden=items.length!==0;document.querySelector('#reviewList').innerHTML=items.map(item=>`<article class="review-card ${item.status} ${item.decision?'done':''}" data-id="${esc(item.id)}"><div class="review-card-rail"></div><div class="review-body"><div class="review-meta"><span class="badge ${item.status}">${item.status==='escalated'?'Human review':'Needs decision'}</span><span>${esc(item.category)}</span><span>·</span><span>${esc(item.source)}</span></div><h3>${esc(item.title)}</h3><p>${esc(item.summary)}</p><div class="review-source">${esc(item.source)} <a href="${esc(item.url)}" target="_blank" rel="noreferrer">Open evidence ↗</a></div></div><div class="review-side"><span class="panel-title">PANEL POSITION</span><div class="votes">${item.votes.map(v=>`<span class="vote-avatar">${esc(v)}</span>`).join('')}<span class="vote-summary"><strong>${item.status==='escalated'?'3':'2'}/4</strong> agree</span></div><p class="review-reason">${esc(item.reason)}</p><div class="review-actions">${item.decision?`<span class="badge">${esc(item.decision)}</span>`:`<button class="approve" data-action="approve">Approve</button><button data-action="reject">Reject</button><button data-action="escalate">Escalate</button><button data-action="correct">Correct</button>`}</div></div></article>`).join('')}
function renderSources(){document.querySelector('#sourceTable').innerHTML='<div class="source-row head"><div>Source</div><div>Status</div><div>Success</div><div>Fresh items</div><div>14-day reliability</div></div>'+sourceRows.map(row=>`<div class="source-row"><div><div class="source-name">${esc(row[0])}</div><div class="source-id">${esc(row[1])}</div></div><div class="source-status ${row[2]==='Warning'?'warn':''}">${row[2]}</div><div>${row[3]}</div><div>${row[4]}</div><div class="bar"><i style="width:${row[3]}"></i></div></div>`).join('')}
function renderAlerts(){document.querySelector('#alertList').innerHTML=alertRows.map(row=>`<div class="alert-row ${row.severity}"><i class="alert-icon"></i><div><strong>${esc(row.title)}</strong><p>${esc(row.detail)}</p></div><time>${esc(row.time)}</time></div>`).join('')}
function setView(view){document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.view===view));document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==`${view}View`)}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>setView(tab.dataset.view)));
document.querySelector('#queueFilter').addEventListener('change',renderReviews);
document.querySelector('#reviewList').addEventListener('click',async event=>{const button=event.target.closest('button[data-action]');if(!button)return;const card=button.closest('[data-id]'), item=reviews.find(x=>x.id===card.dataset.id), action=button.dataset.action;if(action==='correct'){const claim=prompt('Claim to correct');const correction=claim&&prompt('Corrected wording');const reason=correction&&prompt('Reason and evidence for the correction');if(!claim||!correction||!reason)return;try{await apiRequest('/api/ops/corrections',{method:'POST',body:JSON.stringify({edition_id:activeRunId||'pending',story_id:item.id,claim,correction,reason})});toast('Correction recorded in the audit database.')}catch(error){toast(`Correction failed: ${error.message}`)}return}try{await apiRequest('/api/ops/decisions',{method:'POST',body:JSON.stringify({cluster_id:item.id,state:action==='approve'?'approved':action==='reject'?'rejected':'escalated',reason:'Operator decision from control room',run_id:activeRunId})});toast('Decision saved to the operations API.')}catch(error){toast(`API unavailable — saved locally: ${error.message}`)}item.decision=action;item.status=action==='escalate'?'escalated':'done';save();renderReviews()});
document.querySelector('#clearCompleted').addEventListener('click',()=>{reviews=reviews.filter(x=>!x.decision);save();renderReviews();toast('Completed decisions cleared from this workstation.')});
document.querySelector('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),decisions:reviews.filter(x=>x.decision)},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`ai-daily-decisions-${Date.now()}.json`;link.click();URL.revokeObjectURL(link.href);toast('Decision artifact downloaded.')});
document.querySelector('#refreshBtn').addEventListener('click',()=>{toast('Refreshing the control room…');loadLiveData().then(()=>toast('Control room refreshed.'))});
document.querySelector('#logoutBtn').addEventListener('click',()=>{window.location.href='/auth/logout'});
document.querySelector('#publishBtn').addEventListener('click',async()=>{if(!activeRunId)return toast('No active review run found.');try{await apiRequest(`/api/ops/runs/${activeRunId}/publish`,{method:'POST',body:'{}'});toast('Publication run started. Watch health for completion.')}catch(error){toast(`Publication blocked: ${error.message}`)}});
document.querySelector('#pauseSourceBtn').addEventListener('click',async()=>{const source_id=prompt('Source ID to pause (for example openai-news)');if(!source_id)return;try{await apiRequest('/api/ops/sources/pause',{method:'POST',body:JSON.stringify({source_id,paused:true})});toast(`${source_id} paused in the operations API.`)}catch(error){toast(`API unavailable: ${error.message}`)}});
document.querySelector('#ackAlerts').addEventListener('click',()=>{alertRows=[];renderAlerts();toast('Alerts acknowledged on this workstation.')});
document.querySelector('#killSwitch').addEventListener('click',async event=>{const button=event.currentTarget;const on=!button.classList.contains('on');try{await apiRequest('/api/ops/publishing/kill-switch',{method:'POST',body:JSON.stringify({enabled:on})});button.classList.toggle('on',on);button.setAttribute('aria-pressed',String(on));document.querySelector('#killLabel').textContent=on?'Publishing paused':'Publishing enabled';toast(on?'Kill switch active — publication paused.':'Publishing re-enabled.')}catch(error){toast(`API unavailable: ${error.message}`)}});
async function loadLiveData(){try{const [health,sourcePayload,alerts,queue]=await Promise.all([apiRequest('/api/ops/health'),apiRequest('/api/ops/sources'),apiRequest('/api/ops/alerts'),apiRequest('/api/ops/review-queue')]);activeRunId=queue.run_id||null;if(sourcePayload.health)sourceRows=Object.entries(sourcePayload.health).map(([id,row])=>[id.replaceAll('-',' '),id,row.last_status==='ok'?'Healthy':'Warning',`${Math.round((row.successes/Math.max(row.runs,1))*100)}%`,row.last_candidates]);if(queue.review_queue?.length)reviews=queue.review_queue.map(entry=>{const prompt=entry.prompts?.[0];const cluster=prompt?.cluster||{};return {id:entry.cluster_id,status:entry.triage?.high_impact?'escalated':'pending',category:'REVIEW',source:cluster.items?.map(item=>item.source).join(' · ')||'Evidence pending',title:cluster.title||entry.cluster_id,summary:'A live candidate cluster awaiting operator review.',reason:entry.triage?.reason||'The panel requires a decision.',votes:['AL','RK','MO','JP'],decision:null,url:cluster.items?.[0]?.url||'#'}});if(health?.alerts?.length)alertRows=health.alerts.map(a=>({severity:a.severity==='critical'?'critical':'warn',title:a.code,detail:`${a.count||0} affected source(s)`,time:health.completed_at}));renderReviews();renderSources();renderAlerts();return}catch{ /* static demo state keeps the control room useful before API auth/server exists */}try{const [health,sourceIndex,candidate]=await Promise.all([fetch('data/health/last-run.json').then(r=>r.json()),fetch('data/health/sources/index.json').then(r=>r.json()),fetch('data/candidates.json').then(r=>r.json())]);if(sourceIndex)sourceRows=Object.entries(sourceIndex).map(([id,row])=>[id.replaceAll('-',' '),id,row.last_status==='ok'?'Healthy':'Warning',`${Math.round((row.successes/Math.max(row.runs,1))*100)}%`,row.last_candidates]);if(health?.alerts?.length)alertRows=health.alerts.map(a=>({severity:a.severity==='critical'?'critical':'warn',title:a.code,detail:`${a.count||0} affected source(s)`,time:health.completed_at}));if(candidate?.stories?.length)toast(`${candidate.stories.length} candidates loaded from the latest run.`);renderSources();renderAlerts()}catch{ /* static demo state keeps the control room useful before a run exists */}}
renderReviews();renderSources();renderAlerts();loadLiveData();
