import { createHash, randomBytes } from 'node:crypto';
import { createRemoteJWKSet, jwtVerify } from 'jose';
import { createSession, deleteSession, getSession, saveAuthState, takeAuthState, token } from './ops-db.mjs';

const issuer = process.env.OPS_OIDC_ISSUER;
const clientId = process.env.OPS_OIDC_CLIENT_ID;
const clientSecret = process.env.OPS_OIDC_CLIENT_SECRET;
const redirectUri = process.env.OPS_OIDC_REDIRECT_URI || 'http://localhost:4174/auth/callback';
let configuration;
async function oidc() { if (!issuer || !clientId || !clientSecret) throw new Error('OPS_OIDC_ISSUER, OPS_OIDC_CLIENT_ID, and OPS_OIDC_CLIENT_SECRET are required'); if (!configuration) { const response = await fetch(`${issuer.replace(/\/$/,'')}/.well-known/openid-configuration`); if (!response.ok) throw Error(`OIDC discovery failed: ${response.status}`); configuration = await response.json(); } return configuration; }
const b64 = bytes => Buffer.from(bytes).toString('base64url');
const challenge = verifier => b64(createHash('sha256').update(verifier).digest());
function cookies(header='') { return Object.fromEntries(header.split(';').map(part=>part.trim().split('=').map(decodeURIComponent)).filter(pair=>pair.length===2)); }
const secureCookie = process.env.OPS_COOKIE_SECURE !== 'false' ? ' Secure' : '';
export function clearCookie() { return `ops_session=; Max-Age=0; Path=/; HttpOnly;${secureCookie} SameSite=Lax`; }
export async function currentUser(req) { const session=cookies(req.headers.cookie).ops_session; return getSession(session); }
export async function login(res, returnTo='/ops.html') { const config=await oidc();const state=token(),nonce=token(),verifier=token();await saveAuthState(state,nonce,verifier,returnTo);const url=new URL(config.authorization_endpoint);url.searchParams.set('client_id',clientId);url.searchParams.set('redirect_uri',redirectUri);url.searchParams.set('response_type','code');url.searchParams.set('scope','openid profile email');url.searchParams.set('state',state);url.searchParams.set('nonce',nonce);url.searchParams.set('code_challenge',challenge(verifier));url.searchParams.set('code_challenge_method','S256');res.writeHead(302,{location:url.toString()});res.end(); }
export async function callback(res, query) { const config=await oidc();const saved=await takeAuthState(query.get('state'));if(!saved||!query.get('code'))throw Error('invalid or expired OIDC state');const tokenResponse=await fetch(config.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code:query.get('code'),redirect_uri:redirectUri,client_id:clientId,client_secret:clientSecret,code_verifier:saved.code_verifier})});if(!tokenResponse.ok)throw Error('OIDC token exchange failed');const tokens=await tokenResponse.json();const keys=createRemoteJWKSet(new URL(config.jwks_uri));const verified=await jwtVerify(tokens.id_token,keys,{issuer,audience:clientId,nonce:saved.nonce});const claims=verified.payload;const email=String(claims.email||'');if(claims.email_verified===false)throw Error('operator email is not verified');const allowed=(process.env.OPS_ALLOWED_EMAILS||'').split(',').map(v=>v.trim()).filter(Boolean);const domain=process.env.OPS_ALLOWED_DOMAIN;if((allowed.length&&!allowed.includes(email))||(domain&&!email.endsWith(`@${domain}`)))throw Error('operator is not allowlisted');const session=await createSession({sub:String(claims.sub),email,name:String(claims.name||claims.preferred_username||email),roles:claims.roles||[]});res.writeHead(302,{location:saved.redirect_to||'/ops.html','set-cookie':`ops_session=${encodeURIComponent(session)}; Max-Age=28800; Path=/; HttpOnly;${secureCookie} SameSite=Lax`});res.end(); }
export async function logout(req,res){const session=cookies(req.headers.cookie).ops_session;await deleteSession(session);res.writeHead(302,{location:'/ops.html','set-cookie':clearCookie()});res.end();}
